/* Generated by Web Data Administrator on 27/08/2010 16:58:37 */

/* Options selected: database table-schema table-data stored-procedures all-objects comments  */

/****** DATABASE ******/
/****** Object:  Database [thecovencouk_488009_db1]    Script Date: 08/27/2010 16:58:37 ******/
CREATE DATABASE [thecovencouk_488009_db1]
 COLLATE Latin1_General_CI_AS
ALTER DATABASE [thecovencouk_488009_db1] SET COMPATIBILITY_LEVEL = 100
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [thecovencouk_488009_db1].[dbo].[sp_fulltext_database] @action = 'enable'
end
ALTER DATABASE [thecovencouk_488009_db1] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET ANSI_NULLS OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET ANSI_PADDING OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET ANSI_WARNINGS OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET ARITHABORT OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET AUTO_CLOSE OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET AUTO_CREATE_STATISTICS ON 
ALTER DATABASE [thecovencouk_488009_db1] SET AUTO_SHRINK OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [thecovencouk_488009_db1] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [thecovencouk_488009_db1] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET  ENABLE_BROKER 
ALTER DATABASE [thecovencouk_488009_db1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET TRUSTWORTHY OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [thecovencouk_488009_db1] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE [thecovencouk_488009_db1] SET  READ_WRITE 
ALTER DATABASE [thecovencouk_488009_db1] SET RECOVERY SIMPLE 
ALTER DATABASE [thecovencouk_488009_db1] SET  MULTI_USER 
ALTER DATABASE [thecovencouk_488009_db1] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [thecovencouk_488009_db1] SET DB_CHAINING OFF 


GO
use [thecovencouk_488009_db1]
GO

/****** CREATE TABLES/PROCEDURES ETC ******/
/****** Object:  User [uthecov_488009_1]    Script Date: 08/27/2010 16:58:49 ******/
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'uthecov_488009_1')
CREATE USER [uthecov_488009_1] FOR LOGIN [uthecov_488009_1] WITH DEFAULT_SCHEMA=[uthecov_488009_1]
/****** Object:  User [ATLAS\Admins_thecoven.co.u]    Script Date: 08/27/2010 16:58:49 ******/
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'ATLAS\Admins_thecoven.co.u')
CREATE USER [ATLAS\Admins_thecoven.co.u] FOR LOGIN [ATLAS\Admins_thecoven.co.u]
/****** Object:  Schema [uthecov_488009_1]    Script Date: 08/27/2010 16:58:49 ******/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'uthecov_488009_1')
EXEC sys.sp_executesql N'CREATE SCHEMA [uthecov_488009_1] AUTHORIZATION [uthecov_488009_1]'

/****** Object:  Schema [ATLAS\Admins_thecoven.co.u]    Script Date: 08/27/2010 16:58:49 ******/
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = N'ATLAS\Admins_thecoven.co.u')
EXEC sys.sp_executesql N'CREATE SCHEMA [ATLAS\Admins_thecoven.co.u] AUTHORIZATION [ATLAS\Admins_thecoven.co.u]'

/****** Object:  Table [uthecov_488009_1].[viewtree]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[viewtree]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[viewtree](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[page_id] [int] NOT NULL,
	[parent_id] [int] NOT NULL,
	[layout_id] [int] NULL,
	[ordering] [int] NOT NULL,
 CONSTRAINT [PK_viewtree] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[users]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[users]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[login] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[fullname] [varchar](255) NOT NULL,
	[email] [varchar](50) NULL,
	[active] [bit] NOT NULL,
	[permissions] [int] NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[state]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[state]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[state](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](15) NOT NULL,
	[description] [varchar](255) NULL,
 CONSTRAINT [PK_state] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[session_data]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[session_data]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[session_data](
	[session_id] [varchar](50) NOT NULL,
	[user_id] [int] NOT NULL,
	[user_data] [varchar](max) NOT NULL,
	[active] [bit] NOT NULL,
	[session_opened] [datetime] NOT NULL,
	[session_closed] [datetime] NULL
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[page_content_ref]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[page_content_ref]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[page_content_ref](
	[content_id] [int] NOT NULL,
	[page_id] [int] NOT NULL,
	[slot_num] [int] NULL
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[page]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[page]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[page](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[state] [int] NOT NULL,
	[name] [varchar](255) NULL,
	[linktext] [varchar](255) NULL,
	[title] [varchar](255) NULL,
	[description] [varchar](255) NULL,
	[keywords] [varchar](255) NULL,
	[created_date] [datetime] NULL,
	[created_user] [int] NULL,
	[updated_date] [datetime] NULL,
	[updated_user] [int] NULL,
	[layout_id] [int] NULL,
 CONSTRAINT [PK_page] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[layout]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[layout]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[layout](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[layout_url] [varchar](255) NULL,
 CONSTRAINT [PK_layout] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[content_version]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[content_version]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[content_version](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[content_id] [int] NOT NULL,
	[version_id] [int] NOT NULL,
	[state_id] [int] NOT NULL,
	[data] [text] NULL,
	[edit_user] [int] NOT NULL,
	[updated_date] [datetime] NULL,
 CONSTRAINT [PK_content_version] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[content_types]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[content_types]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[content_types](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[description] [varchar](255) NULL,
 CONSTRAINT [PK_content_types] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
/****** Object:  Table [uthecov_488009_1].[content]    Script Date: 08/27/2010 16:58:49 ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[uthecov_488009_1].[content]') AND type in (N'U'))
BEGIN
CREATE TABLE [uthecov_488009_1].[content](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[created_user] [int] NULL,
	[created_date] [datetime] NULL,
	[updated_user] [int] NULL,
	[updated_date] [datetime] NULL,
	[auth_group] [int] NULL,
	[content_type] [int] NULL,
 CONSTRAINT [PK_content] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_viewtree_ordering]') AND type = 'D')
BEGIN
ALTER TABLE [uthecov_488009_1].[viewtree] ADD  CONSTRAINT [DF_viewtree_ordering]  DEFAULT ((0)) FOR [ordering]
END

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_users_active]') AND type = 'D')
BEGIN
ALTER TABLE [uthecov_488009_1].[users] ADD  CONSTRAINT [DF_users_active]  DEFAULT ((1)) FOR [active]
END

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_users_permissions]') AND type = 'D')
BEGIN
ALTER TABLE [uthecov_488009_1].[users] ADD  CONSTRAINT [DF_users_permissions]  DEFAULT ((0)) FOR [permissions]
END


/****** TABLE DATA ******/
/* Data for table content */
SET identity_insert [content] on

INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (1, 'test', 1, '07/05/2010 11:22:02', 1, '07/05/2010 11:22:02', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (2, 'tech_home', 1, '07/06/2010 12:42:06', 1, '07/06/2010 12:42:06', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (3, 'ccms_intro', 1, '07/06/2010 12:46:25', 1, '07/06/2010 12:46:25', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (4, 'index', 1, '12/07/2010 10:57:05', 1, '12/07/2010 10:57:05', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (5, 'test3', 1, '04/08/2010 15:15:26', 1, '04/08/2010 15:15:26', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (6, 'test7', 1, '05/08/2010 16:53:07', 1, '05/08/2010 16:53:07', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (7, 'Stuff', 3, '18/08/2010 17:34:07', 3, '18/08/2010 17:34:07', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (8, 'ccms_docs_home', 1, '25/08/2010 19:47:54', 1, '25/08/2010 19:47:54', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (9, 'lithon_home', 1, '25/08/2010 19:53:12', 1, '25/08/2010 19:53:12', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (10, 'tech-java', 1, '26/08/2010 15:02:57', 1, '26/08/2010 15:02:57', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (11, 'misc-home', 1, '26/08/2010 16:47:52', 1, '26/08/2010 16:47:52', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (12, 'gigs-home', 1, '26/08/2010 16:50:09', 1, '26/08/2010 16:50:09', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (13, 'employment-home', 1, '26/08/2010 16:57:51', 1, '26/08/2010 16:57:51', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (14, 'other-tech-home', 1, '26/08/2010 17:07:35', 1, '26/08/2010 17:07:35', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (15, 'sites-home', 1, '26/08/2010 17:10:00', 1, '26/08/2010 17:10:00', 1, 1)
INSERT [content] ([id], [name], [created_user], [created_date], [updated_user], [updated_date], [auth_group], [content_type]) VALUES (16, 'gigs-sonisphere', 1, '27/08/2010 08:53:08', 1, '27/08/2010 08:53:08', 1, 1)
SET identity_insert [content] off
GO
/* Data for table content_types */
SET identity_insert [content_types] on

INSERT [content_types] ([id], [name], [description]) VALUES (1, 'default', 'Generic catch-all content type')
SET identity_insert [content_types] off
GO
/* Data for table content_version */
SET identity_insert [content_version] on

INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (1, 1, 1, 1, NULL, 1, '07/05/2010 11:22:02')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (2, 1, 2, 1, '<p>this is a test...</p>', 1, '07/05/2010 11:22:20')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (3, 1, 3, 1, '<p>this is a test...</p>
<p><img src="../../images/a_home.gif" alt="a_home.gif" /></p>', 1, '07/05/2010 11:30:46')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (4, 1, 4, 1, '<p>this is a test...</p>
<p><img src="../../images/a_home.gif" alt="a_home.gif" /></p>
<p>and its updated</p>', 1, '12/05/2010 13:11:20')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (6, 2, 2, 1, '<p>Info about the coding and programming I do. Including C#, Java, ASP (SSJS), Perl and some of the projects we have done.</p>', 1, '07/06/2010 12:44:38')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (7, 3, 1, 1, NULL, 1, '07/06/2010 12:46:25')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (8, 3, 2, 1, '<h2>CCMS</h2>
<p>CCMS, or &#39;Clare&#39;s Content Management System&#39;, is a CMS I have been writing. Originally written in Perl and file-system based I have now ported it to classic ASP, with server-side javascript as the scripting language with versioned content and database support.</p>
<p>&nbsp;</p>', 1, '07/06/2010 12:49:35')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (9, 4, 1, 1, NULL, 1, '12/07/2010 10:57:05')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (10, 4, 2, 1, '<p>Welcome to The Coven...</p>
<p>A bit of a mix here - ranging from bloggy type stuff about gigs etc. we have been to, to historical post-grad stuff to full-on techy stuff.</p>
<p>Have fun...&nbsp;</p>', 1, '12/07/2010 10:59:17')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (11, 4, 3, 1, '<p>Welcome to The Coven...</p>
<p>A bit of a mix here - ranging from bloggy type stuff about gigs etc. we have been to, to historical post-grad stuff to full-on techy stuff.</p>
<p>It&#39;s a bit of a scratchpad, so some content will be poo...</p>
<p>Have fun...&nbsp;</p>', 1, '04/08/2010 14:29:38')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (12, 5, 1, 1, NULL, 1, '04/08/2010 15:15:26')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (13, 5, 2, 1, '<p>editing test content...</p>', 1, '04/08/2010 15:15:42')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (14, 6, 1, 1, NULL, 1, '05/08/2010 16:53:07')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (15, 6, 2, 1, '<p>banana fish blurb flapper</p>', 1, '05/08/2010 16:53:26')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (16, 6, 3, 1, '<h2>The Coven</h2>
<p>Here is a description of the page...</p>', 1, '05/08/2010 16:54:33')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (17, 3, 3, 2, '<h2>CCMS</h2>
<p>CCMS, or &#39;Clare&#39;s Content Management System&#39;, is a CMS I have been writing. Originally written in Perl and file-system based I have now ported it to classic ASP, with server-side javascript as the scripting language with versioned content and database support.&nbsp; Trying again.</p>
<p>&nbsp;</p>', 3, '05/08/2010 17:34:46')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (18, 3, 4, 2, '<h2>CCMS</h2>
<p>CCMS, or &#39;Clare&#39;s Content Management System&#39;, is a CMS I have been writing. Originally written in Perl and file-system based I have now ported it to classic ASP, with server-side javascript as the scripting language with versioned content and database support.&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>', 3, '05/08/2010 17:39:57')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (19, 7, 1, 2, '', 3, '18/08/2010 17:34:28')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (20, 7, 2, 2, '<p>Ho ho!</p>', 3, '18/08/2010 17:35:05')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (21, 2, 3, 1, '<p>Here you will find details about the coding and programming I do. Including C#, Java, ASP (SSJS), Perl and some of the projects we have done.</p>', 1, '25/08/2010 17:42:55')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (22, 8, 1, 1, NULL, 1, '25/08/2010 19:47:54')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (23, 8, 2, 1, '<p>Documentation for CCMS</p>', 1, '25/08/2010 19:48:25')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (24, 9, 1, 1, NULL, 1, '25/08/2010 19:53:12')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (25, 9, 2, 1, '<p>We spend a lot of time visiting various stone circles and other neolithic monuments. Here you will find pictures and descriptions of various places we have visited.</p>', 1, '25/08/2010 19:55:14')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (28, 10, 3, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>&nbsp;</p>
<p>
<param name="size" value="380" /></p>
<!-- add 220 for options gutter,add 20 for footer -->
<p>
<param name="zoom" value="2" />
<param name="title" value="test" /></p>', 1, '26/08/2010 15:06:42')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (29, 10, 4, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text\javascript">// <![CDATA[
Document.Write("HELLO!")
// ]]></script>
</p>', 1, '26/08/2010 15:22:17')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (30, 10, 5, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text\javascript">// <![CDATA[
document.write("HELLO!")
// ]]></script>
</p>', 1, '26/08/2010 15:22:52')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (31, 10, 6, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text/javascript">// <![CDATA[
document.write("HELLO!")
// ]]></script>
</p>', 1, '26/08/2010 15:32:49')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (32, 10, 7, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text/javascript">// <![CDATA[
document.write("<applet code=&#39;com.smeghammer.Applettest.class&#39; archive=&#39;mandelbrot1_2.jar&#39; width=600 height=400><param name=&#39;size&#39; value=&#39;380&#39; /><param name=&#39;zoom&#39; value=&#39;2&#39; /><param name=&#39;title&#39; value=&#39;test&#39; /></applet>")
// ]]></script>
</p>', 1, '26/08/2010 15:34:14')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (33, 10, 8, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text/javascript">// <![CDATA[
document.write("<applet code=&#39;com.smeghammer.Applettest.class&#39; archive=&#39;/images/mandelbrot1_2.jar&#39; width=600 height=400><param name=&#39;size&#39; value=&#39;380&#39; /><param name=&#39;zoom&#39; value=&#39;2&#39; /><param name=&#39;title&#39; value=&#39;test&#39; /></applet>")
// ]]></script>
</p>', 1, '26/08/2010 15:35:01')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (34, 10, 9, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text/javascript">// <![CDATA[
document.write("<applet code=com.smeghammer.Applettest.class archive=/images/mandelbrot1_2.jar width=600 height=400><param name=size value=380 /><param name=zoom value=2 /><param name=title value=test /></applet>")
// ]]></script>
</p>', 1, '26/08/2010 15:38:42')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (35, 10, 10, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text/javascript">// <![CDATA[
document.write("<applet code=com.smeghammer.Applettest.class archive=/images/mandelbrot1_2.jar width=600 height=400><param name=size value=380 /><param name=zoom value=2 /><param name=title value=test /></applet>")
// ]]></script>
</p>
<p>Here are some static images from deeper inside the Mandelbrot set:</p>
<p><img src="../../images/mand1.png" alt="Mandelbrot set image" /></p>
<p><img src="../../images/mand2.png" alt="Mandelbrot set image" /></p>', 1, '26/08/2010 15:44:03')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (36, 10, 11, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is:</p>
<p>
<script type="text/javascript">// <![CDATA[
document.write("<applet code=com.smeghammer.Applettest.class archive=/images/mandelbrot1_2.jar width=600 height=400><param name=size value=380 /><param name=zoom value=2 /><param name=title value=test /></applet>")
// ]]></script>
</p>
<p>Here are some static images from deeper inside the Mandelbrot set:</p>
<p><img src="../../images/mand1.png" alt="Mandelbrot set image" /> <img src="../../images/mand2.png" alt="Mandelbrot set image" /></p>', 1, '26/08/2010 15:44:58')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (37, 11, 1, 1, NULL, 1, '26/08/2010 16:47:52')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (38, 11, 2, 1, '<p>Various things that don&#39;t really fit elsewhere.</p>', 1, '26/08/2010 16:48:50')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (39, 12, 1, 1, NULL, 1, '26/08/2010 16:50:09')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (40, 12, 2, 1, '<p>Photos and stuff from some of the gigs we have ben to over the years</p>', 1, '26/08/2010 16:51:06')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (41, 13, 1, 1, NULL, 1, '26/08/2010 16:57:51')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (42, 13, 2, 2, '<h1>Current Position</h1>
<p>I am currently employed as a technical consultant by <a title="OpenText Corporate Site" href="http://www.opentext.com" target="_blank">OpenText</a>, a provider of enterprise content management solutions. My historic background is as a web content management technical solution architect, originally employed by Obtree. My current position at OpenText is as a result of the acquisition of Obtree.</p>', 1, '26/08/2010 17:02:23')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (43, 13, 3, 1, '<h2>Current Position</h2>
<p>I am currently employed as a technical consultant by <a title="OpenText Corporate Site" href="http://www.opentext.com" target="_blank">OpenText</a>, a provider of enterprise content management solutions. My historic background is as a web content management technical solution architect, originally employed by Obtree, a company subsequently acquired by Ixos. My current position at OpenText is as a result of the acquisition of Ixos in 2006.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>', 1, '26/08/2010 17:05:34')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (44, 14, 1, 1, NULL, 1, '26/08/2010 17:07:35')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (45, 14, 2, 1, '<p>Outside of my employment, I do quite a lot of tinkering with computers - both software and hardware.</p>', 1, '26/08/2010 17:09:27')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (46, 15, 1, 1, NULL, 1, '26/08/2010 17:10:00')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (47, 15, 2, 1, '<p>As decribed <a href="../../ccms.asp?nodeid=13">here</a>, I have been playing around with web content management for several years now and I have built and help to maintain a number of websites using a variety of techniques, ranging from flat files, SSIs, perl and ASP. My lovely wife does most of the design and information architecture as that is more her thing than mine.</p>
<h2>Sites</h2>
<ul>
<li><a title="Shaldon Wildlife Trust" href="http://www.shaldonwildlifetrust.org.uk" target="_blank">Shaldon Wildlife Trust</a>. A small zoo in Teignmouth, Devon. I have been involved in the build and maintainance of this site for some years now, and it seems to be doing quite well.</li>
</ul>', 1, '26/08/2010 17:18:19')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (48, 15, 3, 1, '<p>As decribed <a href="../../ccms.asp?nodeid=13">here</a>, I have been playing around with web content management for several years now and I have built and help to maintain a number of websites using a variety of techniques, ranging from flat files, SSIs, perl and ASP. My lovely wife does most of the design and information architecture as that is more her thing than mine.</p>
<p>The links on the right have further technical details for the geeks out there...</p>
<h2>Sites</h2>
<ul>
<li><a title="Shaldon Wildlife Trust" href="http://www.shaldonwildlifetrust.org.uk" target="_blank">Shaldon Wildlife Trust</a>. A small zoo in Teignmouth, Devon. I have been involved in the build and maintainance of this site for some years now, and it seems to be doing quite well.</li>
<li><a title="Advanced Property Developments" href="http://www.apd-homes.co.uk" target="_blank">Advanced Property Developments</a>. A site created using my perl-based CMS for a Bristol-based builder. </li>
</ul>', 1, '26/08/2010 17:23:25')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (49, 15, 4, 1, '<p>As decribed <a href="../../ccms.asp?nodeid=13">here</a>, I have been playing around with web content management for several years now and I have built and help to maintain a number of websites using a variety of techniques, ranging from flat files, SSIs, perl and ASP. My lovely wife does most of the design and information architecture as that is more her thing than mine.</p>
<p>The links on the right have further technical details for the geeks out there...</p>
<h2>Sites</h2>
<ul>
<li><strong><a title="Shaldon Wildlife Trust" href="http://www.shaldonwildlifetrust.org.uk" target="_blank">Shaldon Wildlife Trust</a></strong>. A small zoo in Teignmouth, Devon. I have been involved in the build and maintainance of this site for some years now, and it seems to be doing quite well. It is classic ASP, template based and has a simple news feature to allow the staff to publish news, press releases etc. The visual designs and IA are managed by my wife.</li>
<li><strong><a title="Advanced Property Developments" href="http://www.apd-homes.co.uk" target="_blank">Advanced Property Developments</a></strong>. A site created using my perl-based CMS for a Bristol-based builder.The pages are all fully editable, though this particular example does not have dynamic navigations.</li>
<li><strong><a title="Andrianna Christofi - Model, TV presenter, Singer" href="http://www.andriannachristofi.co.uk" target="_blank">Andrianna Christofi</a></strong>. A website promoting Andrianna&#39;s media presence. It is effectively a <em>curriculum vitae</em> site. It is consructed using simple server-side includes. The visual designs and IA are again managed by my wife.</li>
</ul>', 1, '26/08/2010 17:30:34')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (50, 15, 5, 1, '<p>As decribed <a href="../../ccms.asp?nodeid=13">here</a>, I have been playing around with web content management for several years now and I have built and help to maintain a number of websites using a variety of techniques, ranging from flat files, SSIs, perl and ASP. My lovely wife does most of the design and information architecture as that is more her thing than mine.</p>
<p>The links on the right have further technical details for the geeks out there...</p>
<h2>Sites</h2>
<ul>
<li><strong><a title="Shaldon Wildlife Trust" href="http://www.shaldonwildlifetrust.org.uk" target="_blank">Shaldon Wildlife Trust</a></strong>. A small zoo in Teignmouth, Devon. I have been involved in the build and maintainance of this site for some years now, and it seems to be doing quite well. It is classic ASP, template based and has a simple news feature to allow the staff to publish news, press releases etc. The visual designs and IA are managed by my wife.</li>
<li><strong><a title="Advanced Property Developments" href="http://www.apd-homes.co.uk" target="_blank">Advanced Property Developments</a></strong>. A site created using my perl-based CMS for a Bristol-based builder.The pages are all fully editable, though this particular example does not have dynamic navigations.</li>
<li><strong><a title="Andrianna Christofi - Model, TV presenter, Singer" href="http://www.andriannachristofi.co.uk" target="_blank">Andrianna Christofi</a></strong>. A website promoting Andrianna&#39;s media presence. It is effectively a <em>curriculum vitae</em> site. It is consructed using simple server-side includes. The visual designs and IA are again managed by my wife.</li>
<li><strong><a title="Clement Jewitt, composer" href="http://www.clement-jewitt.co.uk" target="_blank">Clement Jewitt</a></strong>. A personal website, again built using my perl CMS, that has allowed the owner to create, manage and update his content. The site design was once again by my wife.</li>
<li><strong><a title="WeddingFest 07" href="http://www.weddingfest07.co.uk" target="_blank">WeddingFest 07</a></strong>. OK, this one is a bit narcissistic - this is our wedding site... Design by my wife and basic SSI template build by me.</li>
</ul>', 1, '26/08/2010 17:37:08')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (51, 15, 6, 2, '<p>As decribed <a href="../../ccms.asp?nodeid=13">here</a>, I have been playing around with web content management for several years now and I have built and help to maintain a number of websites using a variety of techniques, ranging from flat files, SSIs, perl and ASP. My lovely wife does most of the design and information architecture as that is more her thing than mine.</p>
<p>The links on the right have further technical details for the geeks out there...</p>
<h2>Sites</h2>
<ul>
<li><strong><a title="Shaldon Wildlife Trust" href="http://www.shaldonwildlifetrust.org.uk" target="_blank">Shaldon Wildlife Trust</a></strong>. A small zoo in Teignmouth, Devon. I have been involved in the build and maintainance of this site for some years now, and it seems to be doing quite well. It is classic ASP, template based and has a simple news feature to allow the staff to publish news, press releases etc. The visual designs and IA are managed by my wife.</li>
<li><strong><a title="Advanced Property Developments" href="http://www.apd-homes.co.uk" target="_blank">Advanced Property Developments</a></strong>. A site created using my perl-based CMS for a Bristol-based builder.The pages are all fully editable, though this particular example does not have dynamic navigations.</li>
<li><strong><a title="Andrianna Christofi - Model, TV presenter, Singer" href="http://www.andriannachristofi.co.uk" target="_blank">Andrianna Christofi</a></strong>. A website promoting Andrianna&#39;s media presence. It is effectively a <em>curriculum vitae</em> site. It is consructed using simple server-side includes. The visual designs and IA are again managed by my wife.</li>
<li><strong><a title="Clement Jewitt, composer" href="http://www.clement-jewitt.co.uk" target="_blank">Clement Jewitt</a></strong>. A personal website, again built using my perl CMS, that has allowed the owner to create, manage and update his content. The site design was once again by my wife.</li>
<li><strong><a title="WeddingFest 07" href="http://www.weddingfest07.co.uk" target="_blank">WeddingFest 07</a></strong>. OK, this one is a bit narcissistic - this is our wedding site... Design and basic SSI template build by me.</li>
</ul>', 1, '26/08/2010 17:37:57')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (52, 15, 7, 1, '<p>As decribed <a href="../../ccms.asp?nodeid=13">here</a>, I have been playing around with web content management for several years now and I have built and help to maintain a number of websites using a variety of techniques, ranging from flat files, SSIs, perl and ASP. My lovely wife does most of the design and information architecture as that is more her thing than mine.</p>
<p>The links on the right have further technical details for the geeks out there...</p>
<h2>Sites</h2>
<ul>
<li><strong><a title="Shaldon Wildlife Trust" href="http://www.shaldonwildlifetrust.org.uk" target="_blank">Shaldon Wildlife Trust</a></strong>. A small zoo in Teignmouth, Devon. I have been involved in the build and maintainance of this site for some years now, and it seems to be doing quite well. It is classic ASP, template based and has a simple news feature to allow the staff to publish news, press releases etc. I am in the process of porting it to use teh ASP version of my CMS. The visual designs and IA are managed by my wife.</li>
<li><strong><a title="Advanced Property Developments" href="http://www.apd-homes.co.uk" target="_blank">Advanced Property Developments</a></strong>. A site created using my perl-based CMS for a Bristol-based builder.The pages are all fully editable, though this particular example does not have dynamic navigations.</li>
<li><strong><a title="Andrianna Christofi - Model, TV presenter, Singer" href="http://www.andriannachristofi.co.uk" target="_blank">Andrianna Christofi</a></strong>. A website promoting Andrianna&#39;s media presence. It is effectively a <em>curriculum vitae</em> site. It is consructed using simple server-side includes. The visual designs and IA are again managed by my wife.</li>
<li><strong><a title="Clement Jewitt, composer" href="http://www.clement-jewitt.co.uk" target="_blank">Clement Jewitt</a></strong>. A personal promotional website, again built using my perl CMS, that has allowed the owner to create, manage and update his content. The site design was once again by my wife.</li>
<li><strong><a title="Eidos Inventions" href="http://www.eidos-inventions.co.uk" target="_blank">Eidos Inventions</a></strong>. This site is a sister to the above and aims to be a personal writings, history and media showcase. This site is using my ASP CMS.</li>
<li><strong><a title="WeddingFest 07" href="http://www.weddingfest07.co.uk" target="_blank">WeddingFest 07</a></strong>. OK, this one is a bit narcissistic - this is our wedding site... Design and basic SSI template build by me.</li>
</ul>', 1, '26/08/2010 17:43:31')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (53, 15, 8, 1, '<p>As decribed <a href="../../ccms.asp?nodeid=13">here</a>, I have been playing around with web content management for several years now and I have built and help to maintain a number of websites using a variety of techniques, ranging from flat files, SSIs, perl and ASP. My lovely wife does most of the design and information architecture as that is more her thing than mine.</p>
<p>The links on the right have further technical details for the geeks out there...</p>
<h2>Sites</h2>
<ul>
<li><strong><a title="Shaldon Wildlife Trust" href="http://www.shaldonwildlifetrust.org.uk" target="_blank">Shaldon Wildlife Trust</a></strong>. A small zoo in Teignmouth, Devon. I have been involved in the build and maintainance of this site for some years now, and it seems to be doing quite well. It is classic ASP, template based and has a simple news feature to allow the staff to publish news, press releases etc. I am in the process of porting it to use teh ASP version of my CMS. The visual designs and IA are managed by my wife.</li>
<li><strong><a title="Advanced Property Developments" href="http://www.apd-homes.co.uk" target="_blank">Advanced Property Developments</a></strong>. A site created using my perl-based CMS for a Bristol-based builder.The pages are all fully editable, though this particular example does not have dynamic navigations.</li>
<li><strong><a title="Andrianna Christofi - Model, TV presenter, Singer" href="http://www.andriannachristofi.co.uk" target="_blank">Andrianna Christofi</a></strong>. A website promoting Andrianna&#39;s media presence. It is effectively a <em>curriculum vitae</em> site. It is consructed using simple server-side includes. The visual designs and IA are again managed by my wife.</li>
<li><strong><a title="Clement Jewitt, composer" href="http://www.clement-jewitt.co.uk" target="_blank">Clement Jewitt</a></strong>. A personal promotional website, again built using my perl CMS, that has allowed the owner to create, manage and update his content. The site design was once again by my wife.</li>
<li><strong><a title="Eidos Inventions" href="http://www.eidos-inventions.co.uk" target="_blank">Eidos Inventions</a></strong>. This site is a sister to the above and aims to be a personal writings, history and media showcase. This site is using my ASP CMS. [Note that this is in the early stages of content population]</li>
<li><strong><a title="WeddingFest 07" href="http://www.weddingfest07.co.uk" target="_blank">WeddingFest 07</a></strong>. OK, this one is a bit narcissistic - this is our wedding site... Design and basic SSI template build by me.</li>
</ul>', 1, '26/08/2010 17:44:21')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (54, 3, 5, 1, '<h2>CCMS</h2>
<p>CCMS, or &#39;Clare&#39;s Content Management System&#39;, is a CMS I have been writing. Originally written in Perl and file-system based I have now ported it to classic ASP, with server-side javascript as the scripting language with versioned content and database support.&nbsp;</p>
<p>This site is using the ASP version of CCMS, and is fully manageable - pages, content and navigations are all under the control of the author. They are of course constrained by the underlying site design and code managing the automatic creation of navigations based on the page hierarchy.</p>
<p>I am currently in the early stages of porting CCMS to .NET using C#.</p>
<p>&nbsp;</p>', 1, '26/08/2010 17:53:57')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (55, 10, 12, 1, '<p>The classic learning to code thing - a Mandelbrot set generator. I built this as a learning exercize. I could probably improve it, but it works OK until you reach the limit of double floats...</p>
<p>Anyway, here it is. Use the mouse to click inside the image to zoom in on the click point. You can alter the colour scheme as well:</p>
<p>
<script type="text/javascript">// <![CDATA[
document.write("<applet code=com.smeghammer.Applettest.class archive=/images/mandelbrot1_2.jar width=600 height=400><param name=size value=380 /><param name=zoom value=2 /><param name=title value=test /></applet>")
// ]]></script>
</p>
<p>Here are some static images from deeper inside the Mandelbrot set:</p>
<p><img src="../../images/mand1.png" alt="Mandelbrot set image" /> <img src="../../images/mand2.png" alt="Mandelbrot set image" /></p>', 1, '26/08/2010 17:55:54')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (56, 12, 3, 1, '<p>Photos and stuff from some of the gigs we have been to over the years</p>', 1, '26/08/2010 17:57:30')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (57, 16, 1, 1, NULL, 1, '27/08/2010 08:53:08')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (58, 16, 2, 2, '<p>A new rock festival, first held in 2009. Here is some shit about it.</p>
<h3>2009</h3>
<p>Metallica headlined.</p>
<h3>2010</h3>
<p>Iron Maiden headlined. We got afew decent-ish photos, but my camera reset itself to thumbnail mode, so most of them are tiny...</p>
<p>&nbsp;</p>', 1, '27/08/2010 08:57:26')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (59, 16, 3, 2, '<p>A new rock festival, first held in 2009. Here is some shit about it.</p>
<h3>2009</h3>
<p>Metallica headlined.</p>
<h3>2010</h3>
<p>Iron Maiden headlined. We got afew decent-ish photos, but my camera reset itself to thumbnail mode, so most of them are tiny...</p>
<h4>Voodoo 6</h4>
<p>A surprise! Had heard some of their stuff, but definately better live:</p>
<p><img src="../../images/voodoo6_3.jpg" alt="Voodoo 6" /></p>
<p><img src="../../images/voodoo6_4.jpg" alt="Voodoo 6" /></p>
<p>&nbsp;</p>
<h4>The Union</h4>
<p>Blues rock from some ex-Thunder members. Also pretty good.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>', 1, '27/08/2010 09:02:20')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (60, 16, 4, 1, '<p>A new rock festival, first held in 2009. Here is some shit about it.</p>
<h3>2009</h3>
<p>Metallica headlined.</p>
<h3>2010</h3>
<p>Iron Maiden headlined. We got afew decent-ish photos, but my camera reset itself to thumbnail mode, so most of them are tiny...</p>
<h4>Voodoo 6</h4>
<p>A surprise! Had heard some of their stuff, but definately better live:</p>
<p><img src="../../images/voodoo6_3.jpg" alt="Voodoo 6" /></p>
<p><img src="../../images/voodoo6_4.jpg" alt="Voodoo 6" /></p>
<p>&nbsp;</p>
<h4>The Union</h4>
<p>Blues rock from some ex-Thunder members. Also pretty good.</p>
<p><img src="../../images/theunion_1.jpg" alt="The Union" /></p>
<p>&nbsp;</p>', 1, '27/08/2010 09:03:54')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (61, 16, 5, 2, '<p>A new rock festival, first held in 2009. Here is some shit about it.</p>
<h3>2009</h3>
<p>Metallica headlined.</p>
<h3>2010</h3>
<p>Iron Maiden headlined. We got afew decent-ish photos, but my camera reset itself to thumbnail mode, so most of them are tiny...</p>
<h4>Voodoo 6</h4>
<p>A surprise! Had heard some of their stuff, but definately better live:</p>
<p><img src="../../images/voodoo6_3.jpg" alt="Voodoo 6" /></p>
<p><img src="../../images/voodoo6_4.jpg" alt="Voodoo 6" /></p>
<p>&nbsp;</p>
<h4>The Union</h4>
<p>Blues rock from some ex-Thunder members. Also pretty good.</p>
<p><img src="../../images/theunion_1.jpg" alt="The Union" /></p>
<p>&nbsp;</p>
<h4>Apocalyptica</h4>
<p>Metal! With cellos! Wierd, but works...</p>
<p>&nbsp;</p>
<p>&nbsp;</p>', 1, '27/08/2010 09:05:44')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (62, 16, 6, 2, '<p>A new rock festival, first held in 2009. Here is some shit about it.</p>
<h3>2009</h3>
<p>Metallica headlined.</p>
<h3>2010</h3>
<p>Iron Maiden headlined. We got afew decent-ish photos, but my camera reset itself to thumbnail mode, so most of them are tiny...</p>
<h4>Voodoo 6</h4>
<p>A surprise! Had heard some of their stuff, but definately better live:</p>
<p><img src="../../images/voodoo6_3.jpg" alt="Voodoo 6" /></p>
<p><img src="../../images/voodoo6_4.jpg" alt="Voodoo 6" /></p>
<p>&nbsp;</p>
<h4>The Union</h4>
<p>Blues rock from some ex-Thunder members. Also pretty good.</p>
<p><img src="../../images/theunion_1.jpg" alt="The Union" /></p>
<p>&nbsp;</p>
<h4>Apocalyptica</h4>
<p>Metal! With cellos! Wierd, but works...</p>
<p><img src="../../images/apocalyptica_1.jpg" alt="Apocalyptica" /> <img src="../../images/apocalyptica_2.jpg" alt="Apocalyptica" /> <img src="../../images/apocalyptica_3.jpg" alt="Apocalyptica" /> <img src="../../images/apocalyptica_4.jpg" alt="Apocalyptica" /></p>
<p>&nbsp;</p>
<p>&nbsp;</p>', 1, '27/08/2010 09:10:01')
INSERT [content_version] ([id], [content_id], [version_id], [state_id], [data], [edit_user], [updated_date]) VALUES (63, 16, 7, 1, '<p>A new rock festival, first held in 2009. Here is some shit about it.</p>
<h3>2009</h3>
<p>Metallica headlined.</p>
<h3>2010</h3>
<p>Iron Maiden headlined. We got afew decent-ish photos, but my camera reset itself to thumbnail mode, so most of them are tiny...</p>
<h4>Voodoo 6</h4>
<p>A surprise! Had heard some of their stuff, but definately better live:</p>
<p><img src="../../images/voodoo6_3.jpg" alt="Voodoo 6" /></p>
<p><img src="../../images/voodoo6_4.jpg" alt="Voodoo 6" /></p>
<p>&nbsp;</p>
<h4>The Union</h4>
<p>Blues rock from some ex-Thunder members. Also pretty good.</p>
<p><img src="../../images/theunion_1.jpg" alt="The Union" /></p>
<p>&nbsp;</p>
<h4>Apocalyptica</h4>
<p>Metal! With cellos! Wierd, but works...</p>
<p><img src="../../images/apocalyptica_1.jpg" alt="Apocalyptica" /> <img src="../../images/apocalyptica_2.jpg" alt="Apocalyptica" /></p>
<p><img src="../../images/apocalyptica_3.jpg" alt="Apocalyptica" /> <img src="../../images/apocalyptica_4.jpg" alt="Apocalyptica" /></p>
<p>&nbsp;</p>
<p>&nbsp;</p>', 1, '27/08/2010 09:11:12')
SET identity_insert [content_version] off
GO
/* Data for table layout */
SET identity_insert [layout] on

INSERT [layout] ([id], [layout_url]) VALUES (1, 'coven_index.tmpl')
INSERT [layout] ([id], [layout_url]) VALUES (2, 'coven_content.tmpl')
INSERT [layout] ([id], [layout_url]) VALUES (3, 'default_template.tmpl')
INSERT [layout] ([id], [layout_url]) VALUES (4, 'dad1col.tmpl')
INSERT [layout] ([id], [layout_url]) VALUES (5, 'coven_content_news.tmpl')
SET identity_insert [layout] off
GO
/* Data for table page */
SET identity_insert [page] on

INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (2, 1, 'index', 'Home', 'Home', 'homepage', 'home,index', '05/06/2010 15:12:29', 1, NULL, NULL, 3)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (3, 1, 'sonis_2006', '2006', '2006', '', '', '07/05/2010 11:23:07', 1, '05/06/2010 18:23:46', 1, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (4, 1, 'gigs', 'Gigs', 'Gigs', 'Homepage for our gigs', 'gigs,festvals,download', '05/06/2010 15:07:13', 1, '25/08/2010 19:01:48', 1, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (5, 1, 'download', 'Download', 'Download', '', '', '05/06/2010 15:32:36', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (6, 1, 'sonisphere', 'Sonisphere', 'Sonisphere', '', '', '05/06/2010 15:34:37', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (7, 1, 'dl_2006', '2006', '2006', '', '', '05/06/2010 15:35:43', 1, '05/06/2010 18:24:20', 1, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (8, 1, 'lithon', 'Dead Bothering', 'Dead Bothering', '', '', '07/06/2010 12:36:57', 1, '25/08/2010 19:30:22', 1, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (9, 1, 'tech', 'Techie Stuff', 'Techie Stuff', '', '', '07/06/2010 12:39:42', 1, '25/08/2010 19:45:19', 1, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (10, 1, 'ccms', 'CCMS', 'CCMS', '', '', '07/06/2010 12:45:05', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (11, 1, 'sites', 'Sites', 'Sites', '', '', '07/06/2010 12:45:34', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (12, 1, 'java', 'Java', 'Java', '', '', '07/06/2010 12:45:56', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (13, 1, 'test4', 'Test', 'Test Page', '', '', '04/08/2010 19:22:27', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (14, 1, 'sitesubpage', 'This one!', 'This one!', '', '', '05/08/2010 16:52:30', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (15, 1, 'Test 01', 'Test child', 'Test child', '', '', '18/08/2010 17:58:02', 3, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (16, 1, 'ccms-docs', 'CCMS Documentation', 'CCMS Documentation', 'documentation and downloads for CCMS', 'documents,ccms,download', '25/08/2010 16:56:18', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (17, 1, 'misc', 'Miscellaneous', 'Miscellaneous', 'Various other and historic stuff that does not fit elsewhere', '', '25/08/2010 20:01:21', 1, NULL, NULL, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (18, 1, 'employment-home', 'My Employment', 'My Employment', '', '', '26/08/2010 16:52:03', 1, '26/08/2010 16:57:29', 1, NULL)
INSERT [page] ([id], [state], [name], [linktext], [title], [description], [keywords], [created_date], [created_user], [updated_date], [updated_user], [layout_id]) VALUES (19, 1, 'other-tech-home', 'Other Coding', 'Other Coding', '', '', '26/08/2010 16:53:41', 1, NULL, NULL, NULL)
SET identity_insert [page] off
GO
/* Data for table page_content_ref */
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (2, 9, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (1, 3, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (3, 10, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (4, 2, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (12, 4, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (6, 14, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (7, 13, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (8, 16, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (9, 8, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (14, 19, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (15, 11, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (16, 6, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (10, 12, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (11, 17, 1)
INSERT [page_content_ref] ([content_id], [page_id], [slot_num]) VALUES (13, 18, 1)
/* Data for table session_data */
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('D984C90BA79C0919B64CB890A8E8CA07', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '25/08/2010 12:43:44', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('3C6EA9EEC400874C5335CAE357C7B2B4', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '25/08/2010 16:54:05', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('5E3B2E027217A55BC84003672A2D365A', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '25/08/2010 17:30:41', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('943A1DDCDA75583CCBD89C751B738067', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '25/08/2010 17:42:08', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('0BB2AE93A9A330398D03160465D95C48', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '25/08/2010 18:58:52', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('A25EC9E75968E1A848028611D6C7DA02', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '26/08/2010 15:02:01', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('D75969A6173270B1D3966C2970C923B1', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '26/08/2010 15:32:27', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('BBA3970017163CA107011770B38623DE', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '26/08/2010 21:07:04', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('8A36EA3010ACA0140AE588AB54512CD5', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '25/08/2010 19:50:16', NULL)
INSERT [session_data] ([session_id], [user_id], [user_data], [active], [session_opened], [session_closed]) VALUES ('1C947833A07B37A0C21DB761304040C6', 1, '({id:1,login:''admin'',email:''admin@thecoven.co.uk'',fullName:''Administrator'',permissions:1})', 0, '27/08/2010 08:51:52', NULL)
/* Data for table state */
SET identity_insert [state] on

SET identity_insert [state] off
GO
/* Data for table users */
SET identity_insert [users] on

INSERT [users] ([id], [login], [password], [fullname], [email], [active], [permissions]) VALUES (1, 'admin', 'Asteroth666', 'Administrator', 'admin@thecoven.co.uk', 1, 1)
INSERT [users] ([id], [login], [password], [fullname], [email], [active], [permissions]) VALUES (2, 'silas', 'Asteroth666', 'Silas Jewitt', 'silas@thecoven.co.uk', 1, 1)
INSERT [users] ([id], [login], [password], [fullname], [email], [active], [permissions]) VALUES (3, 'clement', '3ncap5ulati0n', 'Clement Jewitt', '1219cj@phonecoop.coop', 1, 3644)
INSERT [users] ([id], [login], [password], [fullname], [email], [active], [permissions]) VALUES (4, '123-reg', '123-reg', '123-reg test', 'dummy@dummy.com', 0, 44)
INSERT [users] ([id], [login], [password], [fullname], [email], [active], [permissions]) VALUES (5, 'tim', 'timbosearle', 'Tim Searle', 'tim@test.com', 0, 4094)
SET identity_insert [users] off
GO
/* Data for table viewtree */
SET identity_insert [viewtree] on

INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (2, 2, 0, 1, 0)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (4, 4, 2, 2, 0)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (5, 5, 4, NULL, 1)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (6, 6, 4, NULL, 0)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (7, 7, 5, NULL, 0)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (11, 8, 2, 2, 1)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (12, 9, 2, 2, 2)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (13, 10, 23, NULL, 0)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (14, 11, 12, NULL, 2)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (15, 12, 23, NULL, 1)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (20, 16, 13, NULL, 0)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (21, 17, 2, 2, 3)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (22, 18, 12, NULL, 0)
INSERT [viewtree] ([id], [page_id], [parent_id], [layout_id], [ordering]) VALUES (23, 19, 12, NULL, 0)
SET identity_insert [viewtree] off
GO
